matrix:
  include:

    - language: go
      
      sudo: required
      go:
          - 1.13.x

      install: 
          - docker --version
    
          - echo "build discovery"
          - cd discovery
          - pwd
          - sh build

          - echo "build broker"
          - cd ../broker
          - pwd
          - sh build

          - echo "build worker"
          - cd ../worker
          - pwd
          - sh build

          - echo "build master"
          - cd ../master
          - pwd
          - sh build
    
          - echo "build designer"
          - cd ../master
          - pwd
          - sh build    

      before_script:
          - go get -u golang.org/x/lint/golint


      script:

      notifications:
          email: false

    - language: python
      python: 2.7.12
      before_install:
          - echo `python --version`
      before_script:
          - cd test/UnitTest 
      script:
          - py.test
