sudo: required

language: go

go:
    - 1.13.x

install: 
    - docker --version
    
    - echo "build discovery"
    - cd discovery
    - pwd
    - sh build

    - echo "build broker"
    - cd ../broker
    - pwd
    - sh build

    - echo "build worker"
    - cd ../worker
    - pwd
    - sh build

    - echo "build master"
    - cd ../master
    - pwd
    - sh build
    
    - echo "build designer"
    - cd ../master
    - pwd
    - sh build    

    - sudo apt-get update
    - sudo apt-get install python-pip
    - pip -V
    - sudo pip install --upgrade pip
    - pip install Flask
    - pip install requests
    - pip install -U pytest

before_script:
    - go get -u golang.org/x/lint/golint


script:
    - cd ../
    - cd discovery/ 
    - go get
    - go build
    - screen -d -m ./discovery
    - cd ../
    - cd broker/
    - go get
    - go build
    - screen -d -m ./broker
    - cd ../
    - cd test/UnitTest/
    - screen -d -m python accumulator.py
    - cd ../
    - cd UnitTest/v1/
    - pytest -s -v 
    - cd ../
    - cd v2/
    - pytest -s -v
    - echo "Testing Done"

notifications:
    email: false
