sudo: required

language: go

go:
    - 1.13.x

install: 
    - docker --version
    
    - echo "build discovery"
    - cd discovery
    - pwd
    - sh build

    - echo "build broker"
    - cd ../broker
    - pwd
    - sh build

    - echo "build worker"
    - cd ../worker
    - pwd
    - sh build

    - echo "build master"
    - cd ../master
    - pwd
    - sh build
    
    - echo "build designer"
    - cd ../master
    - pwd
    - sh build    

before_script:
    - go get github.com/golang/lint/golint


script:

notifications:
    email: false
