version: "2"
services:
    edge_broker:
        image: fogflow/broker
        volumes:
            - ./config.json:/config.json
        ports:
            - 8890:8890            
    worker:
        image: fogflow/worker
        volumes:
            - ./config.json:/config.json
            - /var/run/docker.sock:/var/run/docker.sock

            
            
