version: "2"
services:
    designer:
        image: fogflow/designer
        volumes:
            - ./config.json:/app/config.json                
        ports:
            - 8080:8080
            - 1030:1030
        depends_on: 
            - discovery
            - cloud_broker
        restart: always
            
    discovery:
        image: fogflow/discovery
        volumes:
            - ./config.json:/config.json                        
        ports:
            - 8090:8090
            - 8092:8092            
        restart: always
        
    master:
        image: fogflow/master
        volumes:
            - ./config.json:/config.json                        
        links:
            - rabbitmq        
        ports:
            - 1060:1060 
        depends_on: 
            - rabbitmq
            - discovery
            - cloud_broker     
        restart: always        
            
    cloud_broker:
        image: fogflow/broker
        volumes:
            - ./config.json:/config.json                        
        ports:
            - 8070:8070
            - 8072:8072     
        depends_on: 
            - discovery
        restart: always
                                        
    cloud_worker:
        image: fogflow/worker
        volumes:
            - /tmp:/tmp        
            - ./config.json:/config.json                
            - /var/run/docker.sock:/var/run/docker.sock      
        restart: always
                                        
    rabbitmq:
        image: rabbitmq:3
        ports:
            - 5672:5672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass   
            
    cadvisor:
      image: google/cadvisor
      ports:
        - 9091:8080
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        
    prometheus:
      image: fogflow/prometheus
      ports:
        - 9090:9090
        - 4545:4545
        
    grafana:
      image: grafana/grafana
      ports:
        - "3000:3000"
      volumes:
        - ./data/grafana:/var/lib/grafana:rw
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false        

    nginx: 
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./designer.pem:/etc/nginx/designer.pem
        - ./designer.key:/etc/nginx/designer.key        
      ports:
        - 443:443
    