version: "3"
services:     
    designer:
        image: fogflow/designer
        volumes:
            - ./config.json:/app/config.json                
        ports:
            - 8080:8080
            - 1030:1030
        depends_on: 
            - discovery
            - cloud_broker
        restart: always
            
    discovery:
        image: fogflow/discovery
        volumes:
            - ./config.json:/config.json                        
        ports:
            - 8090:8090
        restart: always

    master:
        image: fogflow/master
        volumes:
            - ./config.json:/config.json                                   
        links:
            - rabbitmq        
        ports:
            - 1060:1060 
        depends_on: 
            - rabbitmq
            - discovery
            - cloud_broker     
        restart: always 
        
    cloud_broker:
        image: fogflow/broker
        volumes:
            - ./config.json:/config.json 
        ports:
            - 8070:8070
        depends_on: 
            - discovery
        restart: always     
                                        
    cloud_worker:
        image: fogflow/worker
        volumes:
            - /tmp:/tmp        
            - ./config.json:/config.json                            
            - /var/run/docker.sock:/var/run/docker.sock      
        restart: always
                       
    edge_broker1:
        image: fogflow/broker
        volumes:
            - ./edge1.json:/config.json 
        ports:
            - 8170:8170
        depends_on: 
            - discovery
        restart: always                         
                                       
    edge_worker1:
        image: fogflow/worker
        volumes:
            - /tmp:/tmp        
            - ./edge1.json:/config.json                            
            - /var/run/docker.sock:/var/run/docker.sock      
        restart: always                                        

    edge_broker2:
        image: fogflow/broker
        volumes:
            - ./edge2.json:/config.json 
        ports:
            - 8270:8270
        depends_on: 
            - discovery
        restart: always      

    edge_worker2:
        image: fogflow/worker
        volumes:
            - /tmp:/tmp        
            - ./edge2.json:/config.json                            
            - /var/run/docker.sock:/var/run/docker.sock      
        restart: always
                                        
    rabbitmq:
        image: rabbitmq:3
        ports:
            - 5672:5672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass   
        restart: always     
                    
    nginx: 
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      depends_on: 
        - discovery    
        - cloud_broker
        - designer
      restart: always             