version: "3"
services:     
    edge_broker:
        image: fogflow/broker
        volumes:
            - ./config.json:/config.json 
            - ./edge_node.pem:/edge_node.pem
            - ./edge_node.key:/edge_node.key        
            - ./root_ca.pem:/root_ca.pem                                       
        ports:
            - 8070:8070
            - 8072:8072    
        restart: always     
                                        
    edge_worker:
        image: fogflow/worker
        volumes:
            - /tmp:/tmp        
            - ./config.json:/config.json                            
            - /var/run/docker.sock:/var/run/docker.sock      
        depends_on: 
            - edge_broker
        restart: always
                                        

